### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by dhanush-tydy** [editor-js/attaches#49]
when i upload file it's throwing **File upload failed**

**Comment by zerqs** [comment]
same error here. upload is successful but shows modal with error msg  "File upload failed" 
response from server  is sucess: 1

**Comment by GDay** [comment]
@zerqs I got the same error and stumbled on this issue. In my case, the issue was that I wasn't returning the `title` property. If you don't have that in the `file` object, then it will fail due to this:

https://github.com/editor-js/attaches/blob/d80b76f8e505cfe3b1ac65140543f6d35afa0bd3/src/index.js#L283-L297

**Comment by dhanush-tydy** [comment]
> same error here. upload is successful but shows modal with error msg "File upload failed" response from server is sucess: 1

you need to return title property

**Comment by stefanides** [comment]
Just solving the same issue, 
version 1.1.0 works ok without a `title`, 
version 1.2.1 requires a `title` value in the response, but as shows the doc https://github.com/editor-js/attaches#backend-response-format
```
 "file": {
        // any data you want 
        // for example: url, name, size, title
    }
```
that means inside of `file`, not outside `file` object as described here (https://github.com/editor-js/attaches#file-object-) and above in https://github.com/editor-js/attaches/issues/49#issuecomment-1005154504 :disappointed:
